// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: services/candidate-service/proto/candidate.proto

package proto

import (
	
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Candidate entity
type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Experience    string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills        string                 `protobuf:"bytes,7,opt,name=skills,proto3" json:"skills,omitempty"`
	ResumeUrl     string                 `protobuf:"bytes,8,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	LinkedinUrl   string                 `protobuf:"bytes,9,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,10,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	InterviewerId string                 `protobuf:"bytes,14,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Candidate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Candidate) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Candidate) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Candidate) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Candidate) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *Candidate) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

func (x *Candidate) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *Candidate) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *Candidate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Candidate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Candidate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Candidate) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

// Create Candidate
type CreateCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Experience    string                 `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills        string                 `protobuf:"bytes,6,opt,name=skills,proto3" json:"skills,omitempty"`
	ResumeUrl     string                 `protobuf:"bytes,7,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	LinkedinUrl   string                 `protobuf:"bytes,8,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,9,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	InterviewerId string                 `protobuf:"bytes,10,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCandidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCandidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCandidateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCandidateRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateCandidateRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *CreateCandidateRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *CreateCandidateRequest) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

func (x *CreateCandidateRequest) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *CreateCandidateRequest) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *CreateCandidateRequest) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

type CreateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Candidate     *Candidate             `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateResponse) Reset() {
	*x = CreateCandidateResponse{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateResponse) ProtoMessage() {}

func (x *CreateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateResponse.ProtoReflect.Descriptor instead.
func (*CreateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCandidateResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateCandidateResponse) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// Get Candidate
type GetCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateRequest) Reset() {
	*x = GetCandidateRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateRequest) ProtoMessage() {}

func (x *GetCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type GetCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Candidate     *Candidate             `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateResponse) Reset() {
	*x = GetCandidateResponse{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateResponse) ProtoMessage() {}

func (x *GetCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateResponse) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandidateResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetCandidateResponse) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// Get Candidates
type GetCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewerId string                 `protobuf:"bytes,1,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesRequest) Reset() {
	*x = GetCandidatesRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesRequest) ProtoMessage() {}

func (x *GetCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GetCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{5}
}

func (x *GetCandidatesRequest) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

func (x *GetCandidatesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidatesResponse) Reset() {
	*x = GetCandidatesResponse{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidatesResponse) ProtoMessage() {}

func (x *GetCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GetCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{6}
}

func (x *GetCandidatesResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GetCandidatesResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update Candidate
type UpdateCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Experience    string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills        string                 `protobuf:"bytes,7,opt,name=skills,proto3" json:"skills,omitempty"`
	ResumeUrl     string                 `protobuf:"bytes,8,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	LinkedinUrl   string                 `protobuf:"bytes,9,opt,name=linkedin_url,json=linkedinUrl,proto3" json:"linkedin_url,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,10,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateRequest) Reset() {
	*x = UpdateCandidateRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateRequest) ProtoMessage() {}

func (x *UpdateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *UpdateCandidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCandidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCandidateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCandidateRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateCandidateRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *UpdateCandidateRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UpdateCandidateRequest) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

func (x *UpdateCandidateRequest) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *UpdateCandidateRequest) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *UpdateCandidateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Candidate     *Candidate             `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateResponse) Reset() {
	*x = UpdateCandidateResponse{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateResponse) ProtoMessage() {}

func (x *UpdateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCandidateResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateCandidateResponse) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// Delete Candidate
type DeleteCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

// Search Candidates
type SearchCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	InterviewerId string                 `protobuf:"bytes,2,opt,name=interviewer_id,json=interviewerId,proto3" json:"interviewer_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCandidatesRequest) Reset() {
	*x = SearchCandidatesRequest{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCandidatesRequest) ProtoMessage() {}

func (x *SearchCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCandidatesRequest.ProtoReflect.Descriptor instead.
func (*SearchCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCandidatesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCandidatesRequest) GetInterviewerId() string {
	if x != nil {
		return x.InterviewerId
	}
	return ""
}

func (x *SearchCandidatesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCandidatesResponse) Reset() {
	*x = SearchCandidatesResponse{}
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCandidatesResponse) ProtoMessage() {}

func (x *SearchCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_candidate_service_proto_candidate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCandidatesResponse.ProtoReflect.Descriptor instead.
func (*SearchCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_services_candidate_service_proto_candidate_proto_rawDescGZIP(), []int{11}
}

func (x *SearchCandidatesResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SearchCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *SearchCandidatesResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_services_candidate_service_proto_candidate_proto protoreflect.FileDescriptor

const file_services_candidate_service_proto_candidate_proto_rawDesc = "" +
	"\n" +
	"0services/candidate-service/proto/candidate.proto\x12\tcandidate\x1a\x1bservices/proto/common.proto\"\x8d\x03\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\a \x01(\tR\x06skills\x12\x1d\n" +
	"\n" +
	"resume_url\x18\b \x01(\tR\tresumeUrl\x12!\n" +
	"\flinkedin_url\x18\t \x01(\tR\vlinkedinUrl\x12\x1d\n" +
	"\n" +
	"github_url\x18\n" +
	" \x01(\tR\tgithubUrl\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12%\n" +
	"\x0einterviewer_id\x18\x0e \x01(\tR\rinterviewerId\"\xb4\x02\n" +
	"\x16CreateCandidateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"experience\x18\x05 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\x06 \x01(\tR\x06skills\x12\x1d\n" +
	"\n" +
	"resume_url\x18\a \x01(\tR\tresumeUrl\x12!\n" +
	"\flinkedin_url\x18\b \x01(\tR\vlinkedinUrl\x12\x1d\n" +
	"\n" +
	"github_url\x18\t \x01(\tR\tgithubUrl\x12%\n" +
	"\x0einterviewer_id\x18\n" +
	" \x01(\tR\rinterviewerId\"{\n" +
	"\x17CreateCandidateResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x122\n" +
	"\tcandidate\x18\x02 \x01(\v2\x14.candidate.CandidateR\tcandidate\"8\n" +
	"\x13GetCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\"x\n" +
	"\x14GetCandidateResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x122\n" +
	"\tcandidate\x18\x02 \x01(\v2\x14.candidate.CandidateR\tcandidate\"q\n" +
	"\x14GetCandidatesRequest\x12%\n" +
	"\x0einterviewer_id\x18\x01 \x01(\tR\rinterviewerId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xaf\x01\n" +
	"\x15GetCandidatesResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x124\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x14.candidate.CandidateR\n" +
	"candidates\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xc8\x02\n" +
	"\x16UpdateCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\a \x01(\tR\x06skills\x12\x1d\n" +
	"\n" +
	"resume_url\x18\b \x01(\tR\tresumeUrl\x12!\n" +
	"\flinkedin_url\x18\t \x01(\tR\vlinkedinUrl\x12\x1d\n" +
	"\n" +
	"github_url\x18\n" +
	" \x01(\tR\tgithubUrl\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"{\n" +
	"\x17UpdateCandidateResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x122\n" +
	"\tcandidate\x18\x02 \x01(\v2\x14.candidate.CandidateR\tcandidate\";\n" +
	"\x16DeleteCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\"\x8a\x01\n" +
	"\x17SearchCandidatesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x0einterviewer_id\x18\x02 \x01(\tR\rinterviewerId\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xb2\x01\n" +
	"\x18SearchCandidatesResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x124\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x14.candidate.CandidateR\n" +
	"candidates\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination2\x90\x04\n" +
	"\x10CandidateService\x12X\n" +
	"\x0fCreateCandidate\x12!.candidate.CreateCandidateRequest\x1a\".candidate.CreateCandidateResponse\x12O\n" +
	"\fGetCandidate\x12\x1e.candidate.GetCandidateRequest\x1a\x1f.candidate.GetCandidateResponse\x12R\n" +
	"\rGetCandidates\x12\x1f.candidate.GetCandidatesRequest\x1a .candidate.GetCandidatesResponse\x12X\n" +
	"\x0fUpdateCandidate\x12!.candidate.UpdateCandidateRequest\x1a\".candidate.UpdateCandidateResponse\x12F\n" +
	"\x0fDeleteCandidate\x12!.candidate.DeleteCandidateRequest\x1a\x10.common.Response\x12[\n" +
	"\x10SearchCandidates\x12\".candidate.SearchCandidatesRequest\x1a#.candidate.SearchCandidatesResponseB9Z7github.com/inter-verse/services/candidate-service/protob\x06proto3"

var (
	file_services_candidate_service_proto_candidate_proto_rawDescOnce sync.Once
	file_services_candidate_service_proto_candidate_proto_rawDescData []byte
)

func file_services_candidate_service_proto_candidate_proto_rawDescGZIP() []byte {
	file_services_candidate_service_proto_candidate_proto_rawDescOnce.Do(func() {
		file_services_candidate_service_proto_candidate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_candidate_service_proto_candidate_proto_rawDesc), len(file_services_candidate_service_proto_candidate_proto_rawDesc)))
	})
	return file_services_candidate_service_proto_candidate_proto_rawDescData
}

var file_services_candidate_service_proto_candidate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_candidate_service_proto_candidate_proto_goTypes = []any{
	(*Candidate)(nil),                // 0: candidate.Candidate
	(*CreateCandidateRequest)(nil),   // 1: candidate.CreateCandidateRequest
	(*CreateCandidateResponse)(nil),  // 2: candidate.CreateCandidateResponse
	(*GetCandidateRequest)(nil),      // 3: candidate.GetCandidateRequest
	(*GetCandidateResponse)(nil),     // 4: candidate.GetCandidateResponse
	(*GetCandidatesRequest)(nil),     // 5: candidate.GetCandidatesRequest
	(*GetCandidatesResponse)(nil),    // 6: candidate.GetCandidatesResponse
	(*UpdateCandidateRequest)(nil),   // 7: candidate.UpdateCandidateRequest
	(*UpdateCandidateResponse)(nil),  // 8: candidate.UpdateCandidateResponse
	(*DeleteCandidateRequest)(nil),   // 9: candidate.DeleteCandidateRequest
	(*SearchCandidatesRequest)(nil),  // 10: candidate.SearchCandidatesRequest
	(*SearchCandidatesResponse)(nil), // 11: candidate.SearchCandidatesResponse
	(*common.Response)(nil),          // 12: common.Response
	(*common.Pagination)(nil),        // 13: common.Pagination
}
var file_services_candidate_service_proto_candidate_proto_depIdxs = []int32{
	12, // 0: candidate.CreateCandidateResponse.response:type_name -> common.Response
	0,  // 1: candidate.CreateCandidateResponse.candidate:type_name -> candidate.Candidate
	12, // 2: candidate.GetCandidateResponse.response:type_name -> common.Response
	0,  // 3: candidate.GetCandidateResponse.candidate:type_name -> candidate.Candidate
	13, // 4: candidate.GetCandidatesRequest.pagination:type_name -> common.Pagination
	12, // 5: candidate.GetCandidatesResponse.response:type_name -> common.Response
	0,  // 6: candidate.GetCandidatesResponse.candidates:type_name -> candidate.Candidate
	13, // 7: candidate.GetCandidatesResponse.pagination:type_name -> common.Pagination
	12, // 8: candidate.UpdateCandidateResponse.response:type_name -> common.Response
	0,  // 9: candidate.UpdateCandidateResponse.candidate:type_name -> candidate.Candidate
	13, // 10: candidate.SearchCandidatesRequest.pagination:type_name -> common.Pagination
	12, // 11: candidate.SearchCandidatesResponse.response:type_name -> common.Response
	0,  // 12: candidate.SearchCandidatesResponse.candidates:type_name -> candidate.Candidate
	13, // 13: candidate.SearchCandidatesResponse.pagination:type_name -> common.Pagination
	1,  // 14: candidate.CandidateService.CreateCandidate:input_type -> candidate.CreateCandidateRequest
	3,  // 15: candidate.CandidateService.GetCandidate:input_type -> candidate.GetCandidateRequest
	5,  // 16: candidate.CandidateService.GetCandidates:input_type -> candidate.GetCandidatesRequest
	7,  // 17: candidate.CandidateService.UpdateCandidate:input_type -> candidate.UpdateCandidateRequest
	9,  // 18: candidate.CandidateService.DeleteCandidate:input_type -> candidate.DeleteCandidateRequest
	10, // 19: candidate.CandidateService.SearchCandidates:input_type -> candidate.SearchCandidatesRequest
	2,  // 20: candidate.CandidateService.CreateCandidate:output_type -> candidate.CreateCandidateResponse
	4,  // 21: candidate.CandidateService.GetCandidate:output_type -> candidate.GetCandidateResponse
	6,  // 22: candidate.CandidateService.GetCandidates:output_type -> candidate.GetCandidatesResponse
	8,  // 23: candidate.CandidateService.UpdateCandidate:output_type -> candidate.UpdateCandidateResponse
	12, // 24: candidate.CandidateService.DeleteCandidate:output_type -> common.Response
	11, // 25: candidate.CandidateService.SearchCandidates:output_type -> candidate.SearchCandidatesResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_services_candidate_service_proto_candidate_proto_init() }
func file_services_candidate_service_proto_candidate_proto_init() {
	if File_services_candidate_service_proto_candidate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_candidate_service_proto_candidate_proto_rawDesc), len(file_services_candidate_service_proto_candidate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_candidate_service_proto_candidate_proto_goTypes,
		DependencyIndexes: file_services_candidate_service_proto_candidate_proto_depIdxs,
		MessageInfos:      file_services_candidate_service_proto_candidate_proto_msgTypes,
	}.Build()
	File_services_candidate_service_proto_candidate_proto = out.File
	file_services_candidate_service_proto_candidate_proto_goTypes = nil
	file_services_candidate_service_proto_candidate_proto_depIdxs = nil
}
