// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: services/question-service/proto/question.proto

package proto

import (
	
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Question entity
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Technology    string                 `protobuf:"bytes,5,opt,name=technology,proto3" json:"technology,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Answer        string                 `protobuf:"bytes,7,opt,name=answer,proto3" json:"answer,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *Question) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Question) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Question) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Question) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Get Questions
type GetQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *common.Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsRequest) Reset() {
	*x = GetQuestionsRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsRequest) ProtoMessage() {}

func (x *GetQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuestionsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsResponse) Reset() {
	*x = GetQuestionsResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsResponse) ProtoMessage() {}

func (x *GetQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionsResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetQuestionsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get Question
type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuestionResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

// Create Question
type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Technology    string                 `protobuf:"bytes,4,opt,name=technology,proto3" json:"technology,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Answer        string                 `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateQuestionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateQuestionRequest) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *CreateQuestionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateQuestionRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{6}
}

func (x *CreateQuestionResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

// Update Question
type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Technology    string                 `protobuf:"bytes,5,opt,name=technology,proto3" json:"technology,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Answer        string                 `protobuf:"bytes,7,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UpdateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateQuestionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateQuestionRequest) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *UpdateQuestionRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateQuestionRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateQuestionResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

// Delete Question
type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

// Search Questions
type SearchQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsRequest) Reset() {
	*x = SearchQuestionsRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsRequest) ProtoMessage() {}

func (x *SearchQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{10}
}

func (x *SearchQuestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQuestionsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsResponse) Reset() {
	*x = SearchQuestionsResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsResponse) ProtoMessage() {}

func (x *SearchQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{11}
}

func (x *SearchQuestionsResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SearchQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *SearchQuestionsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get Questions by Technology
type GetQuestionsByTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technology    string                 `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
	Difficulty    string                 `protobuf:"bytes,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsByTechnologyRequest) Reset() {
	*x = GetQuestionsByTechnologyRequest{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsByTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsByTechnologyRequest) ProtoMessage() {}

func (x *GetQuestionsByTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsByTechnologyRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionsByTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{12}
}

func (x *GetQuestionsByTechnologyRequest) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *GetQuestionsByTechnologyRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *GetQuestionsByTechnologyRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetQuestionsByTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsByTechnologyResponse) Reset() {
	*x = GetQuestionsByTechnologyResponse{}
	mi := &file_services_question_service_proto_question_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsByTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsByTechnologyResponse) ProtoMessage() {}

func (x *GetQuestionsByTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_question_service_proto_question_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsByTechnologyResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsByTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_services_question_service_proto_question_proto_rawDescGZIP(), []int{13}
}

func (x *GetQuestionsByTechnologyResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetQuestionsByTechnologyResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetQuestionsByTechnologyResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_services_question_service_proto_question_proto protoreflect.FileDescriptor

const file_services_question_service_proto_question_proto_rawDesc = "" +
	"\n" +
	".services/question-service/proto/question.proto\x12\bquestion\x1a\x1bservices/proto/common.proto\"\xf4\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x1e\n" +
	"\n" +
	"technology\x18\x05 \x01(\tR\n" +
	"technology\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06answer\x18\a \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"I\n" +
	"\x13GetQuestionsRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xaa\x01\n" +
	"\x14GetQuestionsResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x120\n" +
	"\tquestions\x18\x02 \x03(\v2\x12.question.QuestionR\tquestions\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"5\n" +
	"\x12GetQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"s\n" +
	"\x13GetQuestionResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x12.\n" +
	"\bquestion\x18\x02 \x01(\v2\x12.question.QuestionR\bquestion\"\xb3\x01\n" +
	"\x15CreateQuestionRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x1e\n" +
	"\n" +
	"technology\x18\x04 \x01(\tR\n" +
	"technology\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06answer\x18\x06 \x01(\tR\x06answer\"v\n" +
	"\x16CreateQuestionResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x12.\n" +
	"\bquestion\x18\x02 \x01(\v2\x12.question.QuestionR\bquestion\"\xd4\x01\n" +
	"\x15UpdateQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x1e\n" +
	"\n" +
	"technology\x18\x05 \x01(\tR\n" +
	"technology\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06answer\x18\a \x01(\tR\x06answer\"v\n" +
	"\x16UpdateQuestionResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x12.\n" +
	"\bquestion\x18\x02 \x01(\v2\x12.question.QuestionR\bquestion\"8\n" +
	"\x15DeleteQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"b\n" +
	"\x16SearchQuestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xad\x01\n" +
	"\x17SearchQuestionsResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x120\n" +
	"\tquestions\x18\x02 \x03(\v2\x12.question.QuestionR\tquestions\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\x95\x01\n" +
	"\x1fGetQuestionsByTechnologyRequest\x12\x1e\n" +
	"\n" +
	"technology\x18\x01 \x01(\tR\n" +
	"technology\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\tR\n" +
	"difficulty\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xb6\x01\n" +
	" GetQuestionsByTechnologyResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x120\n" +
	"\tquestions\x18\x02 \x03(\v2\x12.question.QuestionR\tquestions\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination2\xe6\x04\n" +
	"\x0fQuestionService\x12M\n" +
	"\fGetQuestions\x12\x1d.question.GetQuestionsRequest\x1a\x1e.question.GetQuestionsResponse\x12J\n" +
	"\vGetQuestion\x12\x1c.question.GetQuestionRequest\x1a\x1d.question.GetQuestionResponse\x12S\n" +
	"\x0eCreateQuestion\x12\x1f.question.CreateQuestionRequest\x1a .question.CreateQuestionResponse\x12S\n" +
	"\x0eUpdateQuestion\x12\x1f.question.UpdateQuestionRequest\x1a .question.UpdateQuestionResponse\x12C\n" +
	"\x0eDeleteQuestion\x12\x1f.question.DeleteQuestionRequest\x1a\x10.common.Response\x12V\n" +
	"\x0fSearchQuestions\x12 .question.SearchQuestionsRequest\x1a!.question.SearchQuestionsResponse\x12q\n" +
	"\x18GetQuestionsByTechnology\x12).question.GetQuestionsByTechnologyRequest\x1a*.question.GetQuestionsByTechnologyResponseB8Z6github.com/inter-verse/services/question-service/protob\x06proto3"

var (
	file_services_question_service_proto_question_proto_rawDescOnce sync.Once
	file_services_question_service_proto_question_proto_rawDescData []byte
)

func file_services_question_service_proto_question_proto_rawDescGZIP() []byte {
	file_services_question_service_proto_question_proto_rawDescOnce.Do(func() {
		file_services_question_service_proto_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_question_service_proto_question_proto_rawDesc), len(file_services_question_service_proto_question_proto_rawDesc)))
	})
	return file_services_question_service_proto_question_proto_rawDescData
}

var file_services_question_service_proto_question_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_services_question_service_proto_question_proto_goTypes = []any{
	(*Question)(nil),                         // 0: question.Question
	(*GetQuestionsRequest)(nil),              // 1: question.GetQuestionsRequest
	(*GetQuestionsResponse)(nil),             // 2: question.GetQuestionsResponse
	(*GetQuestionRequest)(nil),               // 3: question.GetQuestionRequest
	(*GetQuestionResponse)(nil),              // 4: question.GetQuestionResponse
	(*CreateQuestionRequest)(nil),            // 5: question.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),           // 6: question.CreateQuestionResponse
	(*UpdateQuestionRequest)(nil),            // 7: question.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),           // 8: question.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),            // 9: question.DeleteQuestionRequest
	(*SearchQuestionsRequest)(nil),           // 10: question.SearchQuestionsRequest
	(*SearchQuestionsResponse)(nil),          // 11: question.SearchQuestionsResponse
	(*GetQuestionsByTechnologyRequest)(nil),  // 12: question.GetQuestionsByTechnologyRequest
	(*GetQuestionsByTechnologyResponse)(nil), // 13: question.GetQuestionsByTechnologyResponse
	(*common.Pagination)(nil),                // 14: common.Pagination
	(*common.Response)(nil),                  // 15: common.Response
}
var file_services_question_service_proto_question_proto_depIdxs = []int32{
	14, // 0: question.GetQuestionsRequest.pagination:type_name -> common.Pagination
	15, // 1: question.GetQuestionsResponse.response:type_name -> common.Response
	0,  // 2: question.GetQuestionsResponse.questions:type_name -> question.Question
	14, // 3: question.GetQuestionsResponse.pagination:type_name -> common.Pagination
	15, // 4: question.GetQuestionResponse.response:type_name -> common.Response
	0,  // 5: question.GetQuestionResponse.question:type_name -> question.Question
	15, // 6: question.CreateQuestionResponse.response:type_name -> common.Response
	0,  // 7: question.CreateQuestionResponse.question:type_name -> question.Question
	15, // 8: question.UpdateQuestionResponse.response:type_name -> common.Response
	0,  // 9: question.UpdateQuestionResponse.question:type_name -> question.Question
	14, // 10: question.SearchQuestionsRequest.pagination:type_name -> common.Pagination
	15, // 11: question.SearchQuestionsResponse.response:type_name -> common.Response
	0,  // 12: question.SearchQuestionsResponse.questions:type_name -> question.Question
	14, // 13: question.SearchQuestionsResponse.pagination:type_name -> common.Pagination
	14, // 14: question.GetQuestionsByTechnologyRequest.pagination:type_name -> common.Pagination
	15, // 15: question.GetQuestionsByTechnologyResponse.response:type_name -> common.Response
	0,  // 16: question.GetQuestionsByTechnologyResponse.questions:type_name -> question.Question
	14, // 17: question.GetQuestionsByTechnologyResponse.pagination:type_name -> common.Pagination
	1,  // 18: question.QuestionService.GetQuestions:input_type -> question.GetQuestionsRequest
	3,  // 19: question.QuestionService.GetQuestion:input_type -> question.GetQuestionRequest
	5,  // 20: question.QuestionService.CreateQuestion:input_type -> question.CreateQuestionRequest
	7,  // 21: question.QuestionService.UpdateQuestion:input_type -> question.UpdateQuestionRequest
	9,  // 22: question.QuestionService.DeleteQuestion:input_type -> question.DeleteQuestionRequest
	10, // 23: question.QuestionService.SearchQuestions:input_type -> question.SearchQuestionsRequest
	12, // 24: question.QuestionService.GetQuestionsByTechnology:input_type -> question.GetQuestionsByTechnologyRequest
	2,  // 25: question.QuestionService.GetQuestions:output_type -> question.GetQuestionsResponse
	4,  // 26: question.QuestionService.GetQuestion:output_type -> question.GetQuestionResponse
	6,  // 27: question.QuestionService.CreateQuestion:output_type -> question.CreateQuestionResponse
	8,  // 28: question.QuestionService.UpdateQuestion:output_type -> question.UpdateQuestionResponse
	15, // 29: question.QuestionService.DeleteQuestion:output_type -> common.Response
	11, // 30: question.QuestionService.SearchQuestions:output_type -> question.SearchQuestionsResponse
	13, // 31: question.QuestionService.GetQuestionsByTechnology:output_type -> question.GetQuestionsByTechnologyResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_services_question_service_proto_question_proto_init() }
func file_services_question_service_proto_question_proto_init() {
	if File_services_question_service_proto_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_question_service_proto_question_proto_rawDesc), len(file_services_question_service_proto_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_question_service_proto_question_proto_goTypes,
		DependencyIndexes: file_services_question_service_proto_question_proto_depIdxs,
		MessageInfos:      file_services_question_service_proto_question_proto_msgTypes,
	}.Build()
	File_services_question_service_proto_question_proto = out.File
	file_services_question_service_proto_question_proto_goTypes = nil
	file_services_question_service_proto_question_proto_depIdxs = nil
}
