// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: services/technology-service/proto/technology.proto

package proto

import (
	
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Technology entity
type Technology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Technology) Reset() {
	*x = Technology{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technology) ProtoMessage() {}

func (x *Technology) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technology.ProtoReflect.Descriptor instead.
func (*Technology) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{0}
}

func (x *Technology) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technology) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Technology) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Technology) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Technology) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Technology) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Get Technologies
type GetTechnologiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *common.Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologiesRequest) Reset() {
	*x = GetTechnologiesRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologiesRequest) ProtoMessage() {}

func (x *GetTechnologiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologiesRequest.ProtoReflect.Descriptor instead.
func (*GetTechnologiesRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{1}
}

func (x *GetTechnologiesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTechnologiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Technologies  []*Technology          `protobuf:"bytes,2,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologiesResponse) Reset() {
	*x = GetTechnologiesResponse{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologiesResponse) ProtoMessage() {}

func (x *GetTechnologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologiesResponse.ProtoReflect.Descriptor instead.
func (*GetTechnologiesResponse) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{2}
}

func (x *GetTechnologiesResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetTechnologiesResponse) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *GetTechnologiesResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get Technology
type GetTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechnologyId  string                 `protobuf:"bytes,1,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologyRequest) Reset() {
	*x = GetTechnologyRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyRequest) ProtoMessage() {}

func (x *GetTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyRequest.ProtoReflect.Descriptor instead.
func (*GetTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{3}
}

func (x *GetTechnologyRequest) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

type GetTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Technology    *Technology            `protobuf:"bytes,2,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologyResponse) Reset() {
	*x = GetTechnologyResponse{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyResponse) ProtoMessage() {}

func (x *GetTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyResponse.ProtoReflect.Descriptor instead.
func (*GetTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{4}
}

func (x *GetTechnologyResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

// Create Technology
type CreateTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTechnologyRequest) Reset() {
	*x = CreateTechnologyRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnologyRequest) ProtoMessage() {}

func (x *CreateTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnologyRequest.ProtoReflect.Descriptor instead.
func (*CreateTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTechnologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTechnologyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTechnologyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTechnologyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Technology    *Technology            `protobuf:"bytes,2,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTechnologyResponse) Reset() {
	*x = CreateTechnologyResponse{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTechnologyResponse) ProtoMessage() {}

func (x *CreateTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTechnologyResponse.ProtoReflect.Descriptor instead.
func (*CreateTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTechnologyResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

// Update Technology
type UpdateTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechnologyId  string                 `protobuf:"bytes,1,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTechnologyRequest) Reset() {
	*x = UpdateTechnologyRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTechnologyRequest) ProtoMessage() {}

func (x *UpdateTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTechnologyRequest.ProtoReflect.Descriptor instead.
func (*UpdateTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTechnologyRequest) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTechnologyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateTechnologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Technology    *Technology            `protobuf:"bytes,2,opt,name=technology,proto3" json:"technology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTechnologyResponse) Reset() {
	*x = UpdateTechnologyResponse{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTechnologyResponse) ProtoMessage() {}

func (x *UpdateTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTechnologyResponse.ProtoReflect.Descriptor instead.
func (*UpdateTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTechnologyResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

// Delete Technology
type DeleteTechnologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechnologyId  string                 `protobuf:"bytes,1,opt,name=technology_id,json=technologyId,proto3" json:"technology_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTechnologyRequest) Reset() {
	*x = DeleteTechnologyRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTechnologyRequest) ProtoMessage() {}

func (x *DeleteTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTechnologyRequest.ProtoReflect.Descriptor instead.
func (*DeleteTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTechnologyRequest) GetTechnologyId() string {
	if x != nil {
		return x.TechnologyId
	}
	return ""
}

// Search Technologies
type SearchTechnologiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTechnologiesRequest) Reset() {
	*x = SearchTechnologiesRequest{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTechnologiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTechnologiesRequest) ProtoMessage() {}

func (x *SearchTechnologiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTechnologiesRequest.ProtoReflect.Descriptor instead.
func (*SearchTechnologiesRequest) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{10}
}

func (x *SearchTechnologiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTechnologiesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchTechnologiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Technologies  []*Technology          `protobuf:"bytes,2,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTechnologiesResponse) Reset() {
	*x = SearchTechnologiesResponse{}
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTechnologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTechnologiesResponse) ProtoMessage() {}

func (x *SearchTechnologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_technology_service_proto_technology_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTechnologiesResponse.ProtoReflect.Descriptor instead.
func (*SearchTechnologiesResponse) Descriptor() ([]byte, []int) {
	return file_services_technology_service_proto_technology_proto_rawDescGZIP(), []int{11}
}

func (x *SearchTechnologiesResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SearchTechnologiesResponse) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *SearchTechnologiesResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_services_technology_service_proto_technology_proto protoreflect.FileDescriptor

const file_services_technology_service_proto_technology_proto_rawDesc = "" +
	"\n" +
	"2services/technology-service/proto/technology.proto\x12\n" +
	"technology\x1a\x1bservices/proto/common.proto\"\xc0\x01\n" +
	"\n" +
	"Technology\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"L\n" +
	"\x16GetTechnologiesRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xb7\x01\n" +
	"\x17GetTechnologiesResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x12:\n" +
	"\ftechnologies\x18\x02 \x03(\v2\x16.technology.TechnologyR\ftechnologies\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\";\n" +
	"\x14GetTechnologyRequest\x12#\n" +
	"\rtechnology_id\x18\x01 \x01(\tR\ftechnologyId\"}\n" +
	"\x15GetTechnologyResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x126\n" +
	"\n" +
	"technology\x18\x02 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\"\x7f\n" +
	"\x17CreateTechnologyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x80\x01\n" +
	"\x18CreateTechnologyResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x126\n" +
	"\n" +
	"technology\x18\x02 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\"\xa4\x01\n" +
	"\x17UpdateTechnologyRequest\x12#\n" +
	"\rtechnology_id\x18\x01 \x01(\tR\ftechnologyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x80\x01\n" +
	"\x18UpdateTechnologyResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x126\n" +
	"\n" +
	"technology\x18\x02 \x01(\v2\x16.technology.TechnologyR\n" +
	"technology\">\n" +
	"\x17DeleteTechnologyRequest\x12#\n" +
	"\rtechnology_id\x18\x01 \x01(\tR\ftechnologyId\"e\n" +
	"\x19SearchTechnologiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xba\x01\n" +
	"\x1aSearchTechnologiesResponse\x12,\n" +
	"\bresponse\x18\x01 \x01(\v2\x10.common.ResponseR\bresponse\x12:\n" +
	"\ftechnologies\x18\x02 \x03(\v2\x16.technology.TechnologyR\ftechnologies\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination2\xb3\x04\n" +
	"\x11TechnologyService\x12Z\n" +
	"\x0fGetTechnologies\x12\".technology.GetTechnologiesRequest\x1a#.technology.GetTechnologiesResponse\x12T\n" +
	"\rGetTechnology\x12 .technology.GetTechnologyRequest\x1a!.technology.GetTechnologyResponse\x12]\n" +
	"\x10CreateTechnology\x12#.technology.CreateTechnologyRequest\x1a$.technology.CreateTechnologyResponse\x12]\n" +
	"\x10UpdateTechnology\x12#.technology.UpdateTechnologyRequest\x1a$.technology.UpdateTechnologyResponse\x12I\n" +
	"\x10DeleteTechnology\x12#.technology.DeleteTechnologyRequest\x1a\x10.common.Response\x12c\n" +
	"\x12SearchTechnologies\x12%.technology.SearchTechnologiesRequest\x1a&.technology.SearchTechnologiesResponseB:Z8github.com/inter-verse/services/technology-service/protob\x06proto3"

var (
	file_services_technology_service_proto_technology_proto_rawDescOnce sync.Once
	file_services_technology_service_proto_technology_proto_rawDescData []byte
)

func file_services_technology_service_proto_technology_proto_rawDescGZIP() []byte {
	file_services_technology_service_proto_technology_proto_rawDescOnce.Do(func() {
		file_services_technology_service_proto_technology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_technology_service_proto_technology_proto_rawDesc), len(file_services_technology_service_proto_technology_proto_rawDesc)))
	})
	return file_services_technology_service_proto_technology_proto_rawDescData
}

var file_services_technology_service_proto_technology_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_technology_service_proto_technology_proto_goTypes = []any{
	(*Technology)(nil),                 // 0: technology.Technology
	(*GetTechnologiesRequest)(nil),     // 1: technology.GetTechnologiesRequest
	(*GetTechnologiesResponse)(nil),    // 2: technology.GetTechnologiesResponse
	(*GetTechnologyRequest)(nil),       // 3: technology.GetTechnologyRequest
	(*GetTechnologyResponse)(nil),      // 4: technology.GetTechnologyResponse
	(*CreateTechnologyRequest)(nil),    // 5: technology.CreateTechnologyRequest
	(*CreateTechnologyResponse)(nil),   // 6: technology.CreateTechnologyResponse
	(*UpdateTechnologyRequest)(nil),    // 7: technology.UpdateTechnologyRequest
	(*UpdateTechnologyResponse)(nil),   // 8: technology.UpdateTechnologyResponse
	(*DeleteTechnologyRequest)(nil),    // 9: technology.DeleteTechnologyRequest
	(*SearchTechnologiesRequest)(nil),  // 10: technology.SearchTechnologiesRequest
	(*SearchTechnologiesResponse)(nil), // 11: technology.SearchTechnologiesResponse
	(*common.Pagination)(nil),          // 12: common.Pagination
	(*common.Response)(nil),            // 13: common.Response
}
var file_services_technology_service_proto_technology_proto_depIdxs = []int32{
	12, // 0: technology.GetTechnologiesRequest.pagination:type_name -> common.Pagination
	13, // 1: technology.GetTechnologiesResponse.response:type_name -> common.Response
	0,  // 2: technology.GetTechnologiesResponse.technologies:type_name -> technology.Technology
	12, // 3: technology.GetTechnologiesResponse.pagination:type_name -> common.Pagination
	13, // 4: technology.GetTechnologyResponse.response:type_name -> common.Response
	0,  // 5: technology.GetTechnologyResponse.technology:type_name -> technology.Technology
	13, // 6: technology.CreateTechnologyResponse.response:type_name -> common.Response
	0,  // 7: technology.CreateTechnologyResponse.technology:type_name -> technology.Technology
	13, // 8: technology.UpdateTechnologyResponse.response:type_name -> common.Response
	0,  // 9: technology.UpdateTechnologyResponse.technology:type_name -> technology.Technology
	12, // 10: technology.SearchTechnologiesRequest.pagination:type_name -> common.Pagination
	13, // 11: technology.SearchTechnologiesResponse.response:type_name -> common.Response
	0,  // 12: technology.SearchTechnologiesResponse.technologies:type_name -> technology.Technology
	12, // 13: technology.SearchTechnologiesResponse.pagination:type_name -> common.Pagination
	1,  // 14: technology.TechnologyService.GetTechnologies:input_type -> technology.GetTechnologiesRequest
	3,  // 15: technology.TechnologyService.GetTechnology:input_type -> technology.GetTechnologyRequest
	5,  // 16: technology.TechnologyService.CreateTechnology:input_type -> technology.CreateTechnologyRequest
	7,  // 17: technology.TechnologyService.UpdateTechnology:input_type -> technology.UpdateTechnologyRequest
	9,  // 18: technology.TechnologyService.DeleteTechnology:input_type -> technology.DeleteTechnologyRequest
	10, // 19: technology.TechnologyService.SearchTechnologies:input_type -> technology.SearchTechnologiesRequest
	2,  // 20: technology.TechnologyService.GetTechnologies:output_type -> technology.GetTechnologiesResponse
	4,  // 21: technology.TechnologyService.GetTechnology:output_type -> technology.GetTechnologyResponse
	6,  // 22: technology.TechnologyService.CreateTechnology:output_type -> technology.CreateTechnologyResponse
	8,  // 23: technology.TechnologyService.UpdateTechnology:output_type -> technology.UpdateTechnologyResponse
	13, // 24: technology.TechnologyService.DeleteTechnology:output_type -> common.Response
	11, // 25: technology.TechnologyService.SearchTechnologies:output_type -> technology.SearchTechnologiesResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_services_technology_service_proto_technology_proto_init() }
func file_services_technology_service_proto_technology_proto_init() {
	if File_services_technology_service_proto_technology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_technology_service_proto_technology_proto_rawDesc), len(file_services_technology_service_proto_technology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_technology_service_proto_technology_proto_goTypes,
		DependencyIndexes: file_services_technology_service_proto_technology_proto_depIdxs,
		MessageInfos:      file_services_technology_service_proto_technology_proto_msgTypes,
	}.Build()
	File_services_technology_service_proto_technology_proto = out.File
	file_services_technology_service_proto_technology_proto_goTypes = nil
	file_services_technology_service_proto_technology_proto_depIdxs = nil
}
